### ISSUE TITLE
Error during cleanup: `failed to delete the file: %INSTALL_ROOT%\Windows Kits\10\bin\10.0.18362.0\chpe`

### ISSUE THREAD

**Issue by perrylets** [Data-Oriented-House/PortableBuildTools#19] opened 2024-07-15 23:26 UTC
I first ran the tool with the options:
* `Create environment setup scripts & add to user environment`
* MSVC Version `14.40.17.10`
* SDK Version `26100`
* Host Arch `x64`
* Target Arch `x64`
* Destination Folder ` D:\Apps\BuildTools\26100`

and it worked perfectly, but when I ran it again with the options:
* `Create environment setup scripts` 
* MSVC Version `14.40.17.10`
* SDK Version `18362`
* Host Arch `x64`
* Target Arch `x64`
* Destination Folder ` D:\Apps\BuildTools\18362`
![Install options](https://github.com/user-attachments/assets/b391b942-0ef9-4bf6-ac36-569c8e19d5c1)

An error message appeared during cleanup saying `failed to delete the file: D:\Apps\BuildTools\18362\Windows Kits\10\bin\10.0.18362.0\chpe`
![Error message](https://github.com/user-attachments/assets/e3252beb-20f5-41f3-9fb1-72b1a0330054)

When I check `D:\Apps\BuildTools\18362\Windows Kits\10\bin\10.0.18362.0` it only has the folders:
* `arm`
* `arm64`
* `x64`
* `x86`
![D:\Apps\BuildTools\18362\Windows Kits\10\bin\10.0.18362.0](https://github.com/user-attachments/assets/98fed8ee-2e7e-4ccb-8300-b89b1045a1bb)

So either `chpe` existed, was deleted, but for some reason there was an error, or PortableBuildTools is trying to delete something that doesn't exist in the first place.

If the error is related to having two MSVC installations with different SDKs I'll have to find something else because Aseprite needs the 18362 version of the SDK to  build.

**Comment by munohikari** [comment] 2024-07-16 14:28
Please try binary see if any errors occur:
https://github.com/Data-Oriented-House/PortableBuildTools/releases/download/v2.4a/pbt_v2.4a.exe

**Comment by perrylets** [comment] 2024-07-16 21:50
I still have the same error

**Comment by munohikari** [comment] 2024-10-21 00:29
Seeing that there are no leads on this issue, and I cannot reproduce it - I'm closing it until you discover something new.

**Closed by munohikari** 2024-10-21 00:29 UTC
